default_agent: kb_search_agent
agents:
  kb_search_agent:
    name: kb_search_agent
    entrypoint: C:/pg/agentcore-hands-on/agentcore/app.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: docker
    source_path: C:\pg\agentcore-hands-on\agentcore
    aws:
      execution_role: arn:aws:iam::391817384261:role/AmazonBedrockAgentCoreSDKRuntime-ap-northeast-1-5101954bf4
      execution_role_auto_create: false
      account: '391817384261'
      region: ap-northeast-1
      ecr_repository: 391817384261.dkr.ecr.ap-northeast-1.amazonaws.com/bedrock-agentcore-kb_search_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: kb_search_agent-Pb3FH1Djkx
      agent_arn: arn:aws:bedrock-agentcore:ap-northeast-1:391817384261:runtime/kb_search_agent-Pb3FH1Djkx
      agent_session_id: 3a029674-ed97-4a4c-9651-0675a0f7ab99
    codebuild:
      project_name: bedrock-agentcore-kb_search_agent-builder
      execution_role: arn:aws:iam::391817384261:role/AmazonBedrockAgentCoreSDKCodeBuild-ap-northeast-1-5101954bf4
      source_bucket: bedrock-agentcore-codebuild-sources-391817384261-ap-northeast-1
    memory:
      mode: STM_ONLY
      memory_id: kb_search_agent_mem-W9ODNgGzYW
      memory_arn: arn:aws:bedrock-agentcore:ap-northeast-1:391817384261:memory/kb_search_agent_mem-W9ODNgGzYW
      memory_name: kb_search_agent_mem
      event_expiry_days: 30
      first_invoke_memory_check_done: true
      was_created_by_toolkit: true
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
